
# docker-compose.yml
# UCWARE Admin API 개발/테스트 스택 정의
#
# 기능
# ----
# - Admin API (FastAPI, 포트 8001)
# - Redis (캐시/로그, 포트 6379)
# - Chroma (VectorDB, 포트 8000)
#
# 의도
# ----
# - 로컬/테스트 환경에서 필수 구성요소를 한 번에 실행할 수 있도록 지원
# - 운영 환경에서는 K8s/Helm 등으로 대체 가능 (이 파일은 개발용 권장)

version: "3.8"

services:
  # ───────────────────────────── Admin API ─────────────────────────────
  app:
    build: .
    container_name: ucware-app
    env_file:
      - .env                  # .env 파일에서 환경변수 로딩
    ports:
      - "8001:8001"           # Admin API (FastAPI) 포트 노출
    depends_on:
      - redis
      - chroma                # Redis/Chroma 준비 후 실행
    volumes:
      - .:/app                # 소스 코드 실시간 반영 (개발 편의용)

  # ───────────────────────────── Redis ─────────────────────────────
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"           # Redis 기본 포트

  # ───────────────────────────── Chroma ─────────────────────────────
  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"           # Chroma HTTP 포트
    environment:
      - IS_PERSISTENT=TRUE    # 데이터 영속 모드 (chroma_db 디렉토리에 저장)


